### ISSUE TITLE
Inconsistent licensing

### ISSUE THREAD

**Issue by k4y3ff** [cognitect/clojure-lab#39]
The main [`README.md`](https://github.com/cognitect/clojure-lab/blob/master/README.md) says this repo is under a Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License, but the [`LICENSE`](https://github.com/cognitect/clojure-lab/blob/master/LICENSE) file reflects the Eclipse Public License (v 1.0).

**Comment by samumbach** [comment]
I think this is on purpose. Creative Commons licenses are _not_ recommended for code, so it should be under an appropriate OSI-approved license. EPL is the de facto standard for Clojure libraries since this is the license used by Clojure and its core libraries.

**Comment by samumbach** [comment]
Though perhaps we need to clarify which parts are under EPL and which are CC.

**Comment by puredanger** [comment]
Sam, this repo is essentially only training materials, not code (although there is a tiny bit of packaging code). The license file was added by lein new before we had really finalized intentions. I think it's more confusing than useful to have it as there is no code here we're trying to protect. The confusion is amplified because gorilla repl packages the content in .clj files.

**Comment by samumbach** [comment]
:+1: to changing to CC across the board for this repo

**Comment by puredanger** [comment]
Done.
